Creation of Array (1D,2D and Multidimennsional array)


In [2]:
#Aim :   To Perform Operation on Creation of Array (1D,2D and Multidimennsional array) using numpy

In [4]:
#Name : SUJIT MAHADEV RATHOD
#Section : 3B
#Roll No.:37
#Subject : PE-I
# Date :03/08/2024

In [6]:
import numpy as np

In [32]:
arr1=np.array([10,20,30,40,50])


In [34]:
arr

array([1, 2, 3, 4, 5, 6])

In [36]:
arr2=np.array([[10,20,30,40,50],[14,25,35,45,55]])
arr2

array([[10, 20, 30, 40, 50],
       [14, 25, 35, 45, 55]])

In [38]:
arr=np.arange(1,5)


In [40]:
arr

array([1, 2, 3, 4])

In [42]:
print(arr[2:4])


[3 4]


In [44]:
print(arr[:5])


[1 2 3 4]


In [46]:
arr

array([1, 2, 3, 4])

In [50]:
arr3=arr1+arr2

In [54]:
arrarr1=np.array((13,43,65,23,78))
arr2=np.array((23,45,64,12,98))
arr3=arr1+arr2


In [56]:
arr3

array([ 36,  88, 129,  35, 176])